title: blue blog
email: aquative@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  기록으로 남기고 싶은 것들 또는 삽질한 내용을 정리하기 위한 페이지
timezone: Asia/Seoul
baseurl: "" # the subpath of your site, e.g. /blog
url: "blue.fiaa.net" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
